export const holes = [
  {
    number: 1,
    par: 4,
    handicapStroke: 11,
    description:
      "A good starting hole to kick off your round – fair without being too difficult. Fairway bunkers and deep rough on the right should persuade you to keep your drive to the left which opens up the green for a clearer approach shot. Bunkers either side of the green await the wayward approach shot.",
    yardages: { red: 332, white: 358, yellow: 384, blue: 401 },
    waterHazards: { left: false, right: false, front: false },
    bunkers: { positions: ["right", "greenside"], count: 2 },
    green: { shape: "oval", size: "medium" },
    holeLayout: { type: "straight", fairwayWidth: "wide" },
    imageUrl: "/courses/bueng-aram/hole-1.jpg",
  },
  {
    number: 2,
    par: 5,
    handicapStroke: 7,
    description:
      "A straight drive would be helpful as trees lurk either side of the fairway. Fairway bunkers on the right should be avoided. The approach shot tends to bounce right and many prefer to roll the ball onto the green from the higher ground on the left. The green is fast and sloped downhill from the back and from left to right– try to avoid going past the flag on the high side which will require a nasty fast downhill putt.",
    yardages: { red: 465, white: 489, yellow: 512, blue: 532 },
    waterHazards: { left: true, right: false, front: false },
    bunkers: { positions: ["left", "right", "greenside"], count: 4 },
    green: { shape: "round", size: "large" },
    holeLayout: { type: "dogleg-left", fairwayWidth: "medium" },
    imageUrl: "/courses/bueng-aram/hole-2.jpg",
  },
  {
    number: 3,
    par: 4,
    handicapStroke: 15,
    description:
      "A shorter par 4 and downhill too. Make sure to take a note of the 4th green flag position when you are standing on the tee. Then enjoy the view over Bangor before keeping your drive clear of the trees on the right. A decent drive anywhere on the fairway or light rough leaves a 'reasonably' straightforward pitch over the bunkers which surround the green. The green can be a badge fast so be gentle.",
    yardages: { red: 345, white: 368, yellow: 389, blue: 412 },
    waterHazards: { left: false, right: true, front: false },
    bunkers: { positions: ["left", "greenside"], count: 3 },
    green: { shape: "kidney", size: "medium" },
    holeLayout: { type: "dogleg-right", fairwayWidth: "medium" },
    imageUrl: "/courses/bueng-aram/hole-3.jpg",
  },
  {
    number: 4,
    par: 5,
    handicapStroke: 17,
    description:
      "The first par 5 of the course. Not overly long but up a steep hill that takes distance off your second shot. Trees down both sides of the fairway await a wayward drive. Depending on how far back you are, your final approach shot to the green may be blind (aim for the mobile mast if you are unsure). The 4th green is relatively narrow but long, and club selection is vital to avoid a difficult two putt challenge from over 40 feet.",
    yardages: { red: 142, white: 165, yellow: 182, blue: 198 },
    waterHazards: { left: false, right: false, front: true },
    bunkers: { positions: ["left", "right", "greenside"], count: 3 },
    green: { shape: "round", size: "small" },
    holeLayout: { type: "straight", fairwayWidth: "narrow" },
    imageUrl: "/courses/bueng-aram/hole-4.jpg",
  },
  {
    number: 5,
    par: 4,
    handicapStroke: 3,
    description:
      "Stroke index 1 – a dog leg to the right around overhanging trees. Big hitters can cut the corner or fade the ball around the trees to leave the green reachable in two shots. The rest of us will settle for a safe drive to the middle of the fairway and a second shot laying up before the path in front of the green. A clever chip or pitch might get you close enough to have a chance of par but a bogey is a welcome result for most.",
    yardages: { red: 378, white: 398, yellow: 422, blue: 445 },
    waterHazards: { left: true, right: false, front: false },
    bunkers: { positions: ["right", "greenside"], count: 4 },
    green: { shape: "oval", size: "medium" },
    holeLayout: { type: "dogleg-left", fairwayWidth: "narrow" },
    imageUrl: "/courses/bueng-aram/hole-5.jpg",
  },
  {
    number: 6,
    par: 5,
    handicapStroke: 9,
    description:
      "Stroke index says this is an easy hole. But not always. If you can place your drive on the left of the fairway and get a flat lie the second shot is easier. If you go right the ball will be below your feet. If the wind is blowing hard down the fairway the approach will be longer and more difficult. And the green has a few undulations to test your green reading skills. Be happy if you get a par.",
    yardages: { red: 482, white: 508, yellow: 532, blue: 556 },
    waterHazards: { left: false, right: true, front: false },
    bunkers: { positions: ["left", "right", "greenside"], count: 5 },
    green: { shape: "round", size: "large" },
    holeLayout: { type: "straight", fairwayWidth: "wide" },
    imageUrl: "/courses/bueng-aram/hole-6.jpg",
  },
  {
    number: 7,
    par: 4,
    handicapStroke: 5,
    description:
      "First par 3, the longest and lowest stroke index. There are bunkers either side and in front. If you can hit a straight tee shot then you should find the green. Strange that so many don't do that. If you miss you will have a challenging and often interesting little chip or pitch over bunkers or out of the thicker rough around the green.",
    yardages: { red: 365, white: 388, yellow: 412, blue: 435 },
    waterHazards: { left: true, right: false, front: true },
    bunkers: { positions: ["right", "greenside"], count: 3 },
    green: { shape: "kidney", size: "medium" },
    holeLayout: { type: "dogleg-right", fairwayWidth: "medium" },
    imageUrl: "/courses/bueng-aram/hole-7.jpg",
  },
  {
    number: 8,
    par: 3,
    handicapStroke: 13,
    description:
      "A great hole with great views over Bangor and Belfast Lough. It's a wide fairway but position is important. Favour the centre or a wee bit left as there is an aged hawthorne tree, 30 yards in front of the green to the right. The green will run from right to left, sharply at times, and in dry conditions is fast – many a perfect shot has bounced high in front of the green and watched from afar as it races through over the back into thickish rough. For putting, one of the trickiest greens on the course with many levels and contours.",
    yardages: { red: 156, white: 178, yellow: 198, blue: 212 },
    waterHazards: { left: false, right: true, front: true },
    bunkers: { positions: ["left", "right", "greenside"], count: 2 },
    green: { shape: "round", size: "small" },
    holeLayout: { type: "straight", fairwayWidth: "narrow" },
    imageUrl: "/courses/bueng-aram/hole-8.jpg",
  },
  {
    number: 9,
    par: 4,
    handicapStroke: 1,
    description:
      "Par 4 downhill. Keep your drive in a good position centre or left on the wide fairway – right side may require a bit of a fade around the trees for your second shot. Also for the second be aware that you don't always get the perfect lie on this corrugated fairway(uphill, downhill and/or below feet) and this can affect the shape of your approach shot. And there is a heavily wooded area on the right that is tempting for the golfer who prefers to fade the ball and similar on the left for the golfer who likes to hook. A well protected green on two levels awaits.",
    yardages: { red: 389, white: 412, yellow: 435, blue: 458 },
    waterHazards: { left: true, right: false, front: false },
    bunkers: { positions: ["left", "right", "greenside"], count: 4 },
    green: { shape: "oval", size: "large" },
    holeLayout: { type: "dogleg-left", fairwayWidth: "medium" },
    imageUrl: "/courses/bueng-aram/hole-9.jpg",
  },
  {
    number: 10,
    par: 4,
    handicapStroke: 12,
    description:
      "Par 4 uphill. A long hole that many will find difficult to reach in two. The green sits at the top of a hill and the putting surface is hidden from view. If your approach falls just short of the green expect to see the ball roll backwards down the hill. The green is fast and slopes towards the hill – be careful if the flag is at the front of the green.",
    yardages: { red: 345, white: 368, yellow: 392, blue: 415 },
    waterHazards: { left: false, right: true, front: false },
    bunkers: { positions: ["left", "greenside"], count: 3 },
    green: { shape: "round", size: "medium" },
    holeLayout: { type: "straight", fairwayWidth: "medium" },
    imageUrl: "/courses/bueng-aram/hole-10.jpg",
  },
  {
    number: 11,
    par: 5,
    handicapStroke: 8,
    description:
      "A short Par 4. Keep your drive to the centre or left of the fairway for a level lie and view of the green for your second – a drive to the right side may bounce off down the slope, leaving the green out of view over the hill and making your approach shot more difficult.",
    yardages: { red: 475, white: 498, yellow: 522, blue: 545 },
    waterHazards: { left: true, right: false, front: false },
    bunkers: { positions: ["right", "greenside"], count: 4 },
    green: { shape: "kidney", size: "large" },
    holeLayout: { type: "dogleg-right", fairwayWidth: "wide" },
    imageUrl: "/courses/bueng-aram/hole-11.jpg",
  },
  {
    number: 12,
    par: 3,
    handicapStroke: 16,
    description:
      "A short and simple hole that many will par on a good day and also offers an opportunity to bag a '2'. Bunkers either side await the wayward shot but the front of the green is clear making the approach relatively straightforward.",
    yardages: { red: 145, white: 168, yellow: 185, blue: 202 },
    waterHazards: { left: false, right: false, front: true },
    bunkers: { positions: ["left", "right", "greenside"], count: 2 },
    green: { shape: "round", size: "small" },
    holeLayout: { type: "straight", fairwayWidth: "narrow" },
    imageUrl: "/courses/bueng-aram/hole-12.jpg",
  },
  {
    number: 13,
    par: 4,
    handicapStroke: 4,
    description:
      "Recently renovated, this is a long dogleg right. On the left hand side of the fairway there are trees, a pond, bunkers and houses. The trees on the right have been cut back making a drive to the right hand side the preferred option to shorten the hole. The front sides of the green are guarded by bunkers making the entrance narrow. The green is long and narrow making direction and club selection important to landing the ball near the flag.",
    yardages: { red: 382, white: 405, yellow: 428, blue: 452 },
    waterHazards: { left: true, right: false, front: true },
    bunkers: { positions: ["right", "greenside"], count: 3 },
    green: { shape: "oval", size: "medium" },
    holeLayout: { type: "dogleg-left", fairwayWidth: "medium" },
    imageUrl: "/courses/bueng-aram/hole-13.jpg",
  },
  {
    number: 14,
    par: 4,
    handicapStroke: 14,
    description:
      "A short hole with a green bordered by trees on both sides and a couple of bunkers down the left hand side. If you can keep it straight then you should get a par but a fade or draw could leave you in a spot of bother.",
    yardages: { red: 355, white: 378, yellow: 402, blue: 425 },
    waterHazards: { left: false, right: true, front: false },
    bunkers: { positions: ["left", "greenside"], count: 3 },
    green: { shape: "round", size: "medium" },
    holeLayout: { type: "straight", fairwayWidth: "wide" },
    imageUrl: "/courses/bueng-aram/hole-14.jpg",
  },
  {
    number: 15,
    par: 5,
    handicapStroke: 6,
    description:
      "A great hole that will test your golfing skills. It's a dogleg left that requires a long well directed drive to provide sight of the raised green. A drive to the wide right hand side of the fairway is easier but leaves the ball further from the green. Many will opt for a three-shot strategy. The green is on two levels and is protected by bunkers either side.",
    yardages: { red: 478, white: 502, yellow: 525, blue: 548 },
    waterHazards: { left: true, right: false, front: false },
    bunkers: { positions: ["left", "right", "greenside"], count: 5 },
    green: { shape: "kidney", size: "large" },
    holeLayout: { type: "dogleg-left", fairwayWidth: "medium" },
    imageUrl: "/courses/bueng-aram/hole-15.jpg",
  },
  {
    number: 16,
    par: 3,
    handicapStroke: 18,
    description:
      "A Par 5 hole from the top of the course to the bottom. There are great views over the lough and the Antrim Hills. A long straight drive will give some the chance to reach the green in two. Others will need to navigate their second around or over the large bunker on the left of the fairway. The green is long and quite narrow with two large bunkers either side. The putting surface is fast and you need to be careful not to race through the green over the back of the steep bank at the back and sides.",
    yardages: { red: 152, white: 172, yellow: 188, blue: 205 },
    waterHazards: { left: false, right: true, front: true },
    bunkers: { positions: ["left", "greenside"], count: 2 },
    green: { shape: "round", size: "small" },
    holeLayout: { type: "straight", fairwayWidth: "narrow" },
    imageUrl: "/courses/bueng-aram/hole-16.jpg",
  },
  {
    number: 17,
    par: 4,
    handicapStroke: 2,
    description:
      "Another Par 3 and an opportunity for a '2'. The green has bunkers to the left and front right.",
    yardages: { red: 385, white: 408, yellow: 432, blue: 455 },
    waterHazards: { left: true, right: false, front: true },
    bunkers: { positions: ["right", "greenside"], count: 4 },
    green: { shape: "oval", size: "medium" },
    holeLayout: { type: "dogleg-right", fairwayWidth: "narrow" },
    imageUrl: "/courses/bueng-aram/hole-17.jpg",
  },
  {
    number: 18,
    par: 5,
    handicapStroke: 10,
    description:
      "The final hole, a par 4. The wide fairway has thick trees on the right which will block your approach and bunkers either side. The green is raised and is on two levels and is well guarded by two bunkers at the front and a third at the rear left. Being on the wrong level will make two putting a challenge particularly if the flag is at the front of the green.",
    yardages: { red: 485, white: 508, yellow: 532, blue: 555 },
    waterHazards: { left: false, right: true, front: false },
    bunkers: { positions: ["left", "right", "greenside"], count: 5 },
    green: { shape: "round", size: "large" },
    holeLayout: { type: "dogleg-left", fairwayWidth: "wide" },
    imageUrl: "/courses/bueng-aram/hole-18.jpg",
  },
];
