// app/api/seed/courses/data.ts
import { IHole } from "@/models/Hole";

export const coursesData = [
  {
    name: "Bueng Aram Golf Club",
    description:
      "A prestigious golf club nestled in the heart of northeastern Thailand, featuring a challenging parkland layout with stunning lake views and meticulously maintained fairways. The course offers a perfect blend of strategic challenge and natural beauty, making it a must-play destination for golf enthusiasts.",
    layout: {
      totalHoles: 18,
      totalPar: 72,
      courseType: "lakeside" as const,
      terrain: "Rolling parkland with lakeside features",
      waterFeatures: {
        mainLake: true,
        streams: true,
        ponds: 5,
      },
    },
    facilities: {
      drivingRange: {
        available: true,
        underRenovation: false,
      },
      practice: {
        puttingGreen: true,
        chippingArea: true,
      },
      clubhouse: {
        available: true,
        amenities: [
          "Pro Shop",
          "Thai & International Restaurant",
          "Locker Rooms with Sauna",
          "Golf Cart Rental",
          "Club Rental Service",
          "Swimming Pool",
          "Function Rooms",
          "Golf Academy",
        ],
      },
    },
    overallRating: {
      difficulty: 4,
      maintenance: 5,
      scenic: 5,
    },
    gpsCoordinates: {
      latitude: 16.39473,
      longitude: 103.3348,
    },
    mainImageUrls: [
      "/courses/course-1.jpg",
      "/courses/course-2.jpg",
      "/courses/course-3.jpg",
      "/courses/course-4.jpg",
      "/courses/course-5.jpg",
      "/courses/course-6.jpg",
      "/courses/course-7.jpg",
      "/courses/course-8.jpg",
      "/courses/course-9.jpg",
      "/courses/course-10.jpg",
      "/courses/course-11.jpg",
      "/courses/course-12.jpg",
      "/courses/course-13.jpg",
      "/courses/course-14.jpg",
      "/courses/course-15.jpg",
    ],
    holeLayouts: [
      "/courses/bueng-aram/hole-1.jpg",
      "/courses/bueng-aram/hole-2.jpg",
      "/courses/bueng-aram/hole-3.jpg",
      "/courses/bueng-aram/hole-4.jpg",
      "/courses/bueng-aram/hole-5.jpg",
      "/courses/bueng-aram/hole-6.jpg",
      "/courses/bueng-aram/hole-7.jpg",
      "/courses/bueng-aram/hole-8.jpg",
      "/courses/bueng-aram/hole-9.jpg",
      "/courses/bueng-aram/hole-10.jpg",
      "/courses/bueng-aram/hole-11.jpg",
      "/courses/bueng-aram/hole-12.jpg",
      "/courses/bueng-aram/hole-13.jpg",
      "/courses/bueng-aram/hole-14.jpg",
      "/courses/bueng-aram/hole-15.jpg",
      "/courses/bueng-aram/hole-16.jpg",
      "/courses/bueng-aram/hole-17.jpg",
      "/courses/bueng-aram/hole-18.jpg",
    ],
  },
];

// Generate realistic holes for Bueng Aram Golf Club
export const holesData = {
  generateHoles: () => {
    const holes: Partial<IHole>[] = [
      // Front Nine
      {
        number: 1,
        par: 4,
        handicapStroke: 11,
        yardages: { red: 332, white: 358, yellow: 384, blue: 401 },
        waterHazards: { left: false, right: false, front: false },
        bunkers: { positions: ["right", "greenside"], count: 2 },
        green: { shape: "oval", size: "medium" },
        holeLayout: { type: "straight", fairwayWidth: "wide" },
        imageUrl: "/courses/bueng-aram/hole-1.jpg",
      },
      {
        number: 2,
        par: 5,
        handicapStroke: 7,
        yardages: { red: 465, white: 489, yellow: 512, blue: 532 },
        waterHazards: { left: true, right: false, front: false },
        bunkers: { positions: ["left", "right", "greenside"], count: 4 },
        green: { shape: "round", size: "large" },
        holeLayout: { type: "dogleg-left", fairwayWidth: "medium" },
        imageUrl: "/courses/bueng-aram/hole-2.jpg",
      },
      {
        number: 3,
        par: 4,
        handicapStroke: 15,
        yardages: { red: 345, white: 368, yellow: 389, blue: 412 },
        waterHazards: { left: false, right: true, front: false },
        bunkers: { positions: ["left", "greenside"], count: 3 },
        green: { shape: "kidney", size: "medium" },
        holeLayout: { type: "dogleg-right", fairwayWidth: "medium" },
        imageUrl: "/courses/bueng-aram/hole-3.jpg",
      },
      {
        number: 4,
        par: 3,
        handicapStroke: 17,
        yardages: { red: 142, white: 165, yellow: 182, blue: 198 },
        waterHazards: { left: false, right: false, front: true },
        bunkers: { positions: ["left", "right", "greenside"], count: 3 },
        green: { shape: "round", size: "small" },
        holeLayout: { type: "straight", fairwayWidth: "narrow" },
        imageUrl: "/courses/bueng-aram/hole-4.jpg",
      },
      {
        number: 5,
        par: 4,
        handicapStroke: 3,
        yardages: { red: 378, white: 398, yellow: 422, blue: 445 },
        waterHazards: { left: true, right: false, front: false },
        bunkers: { positions: ["right", "greenside"], count: 4 },
        green: { shape: "oval", size: "medium" },
        holeLayout: { type: "dogleg-left", fairwayWidth: "narrow" },
        imageUrl: "/courses/bueng-aram/hole-5.jpg",
      },
      {
        number: 6,
        par: 5,
        handicapStroke: 9,
        yardages: { red: 482, white: 508, yellow: 532, blue: 556 },
        waterHazards: { left: false, right: true, front: false },
        bunkers: { positions: ["left", "right", "greenside"], count: 5 },
        green: { shape: "round", size: "large" },
        holeLayout: { type: "straight", fairwayWidth: "wide" },
        imageUrl: "/courses/bueng-aram/hole-6.jpg",
      },
      {
        number: 7,
        par: 4,
        handicapStroke: 5,
        yardages: { red: 365, white: 388, yellow: 412, blue: 435 },
        waterHazards: { left: true, right: false, front: true },
        bunkers: { positions: ["right", "greenside"], count: 3 },
        green: { shape: "kidney", size: "medium" },
        holeLayout: { type: "dogleg-right", fairwayWidth: "medium" },
        imageUrl: "/courses/bueng-aram/hole-7.jpg",
      },
      {
        number: 8,
        par: 3,
        handicapStroke: 13,
        yardages: { red: 156, white: 178, yellow: 198, blue: 212 },
        waterHazards: { left: false, right: true, front: true },
        bunkers: { positions: ["left", "right", "greenside"], count: 2 },
        green: { shape: "round", size: "small" },
        holeLayout: { type: "straight", fairwayWidth: "narrow" },
        imageUrl: "/courses/bueng-aram/hole-8.jpg",
      },
      {
        number: 9,
        par: 4,
        handicapStroke: 1,
        yardages: { red: 389, white: 412, yellow: 435, blue: 458 },
        waterHazards: { left: true, right: false, front: false },
        bunkers: { positions: ["left", "right", "greenside"], count: 4 },
        green: { shape: "oval", size: "large" },
        holeLayout: { type: "dogleg-left", fairwayWidth: "medium" },
        imageUrl: "/courses/bueng-aram/hole-9.jpg",
      },
      // Back Nine
      {
        number: 10,
        par: 4,
        handicapStroke: 12,
        yardages: { red: 345, white: 368, yellow: 392, blue: 415 },
        waterHazards: { left: false, right: true, front: false },
        bunkers: { positions: ["left", "greenside"], count: 3 },
        green: { shape: "round", size: "medium" },
        holeLayout: { type: "straight", fairwayWidth: "medium" },
        imageUrl: "/courses/bueng-aram/hole-10.jpg",
      },
      {
        number: 11,
        par: 5,
        handicapStroke: 8,
        yardages: { red: 475, white: 498, yellow: 522, blue: 545 },
        waterHazards: { left: true, right: false, front: false },
        bunkers: { positions: ["right", "greenside"], count: 4 },
        green: { shape: "kidney", size: "large" },
        holeLayout: { type: "dogleg-right", fairwayWidth: "wide" },
        imageUrl: "/courses/bueng-aram/hole-11.jpg",
      },
      {
        number: 12,
        par: 3,
        handicapStroke: 16,
        yardages: { red: 145, white: 168, yellow: 185, blue: 202 },
        waterHazards: { left: false, right: false, front: true },
        bunkers: { positions: ["left", "right", "greenside"], count: 2 },
        green: { shape: "round", size: "small" },
        holeLayout: { type: "straight", fairwayWidth: "narrow" },
        imageUrl: "/courses/bueng-aram/hole-12.jpg",
      },
      {
        number: 13,
        par: 4,
        handicapStroke: 4,
        yardages: { red: 382, white: 405, yellow: 428, blue: 452 },
        waterHazards: { left: true, right: false, front: true },
        bunkers: { positions: ["right", "greenside"], count: 3 },
        green: { shape: "oval", size: "medium" },
        holeLayout: { type: "dogleg-left", fairwayWidth: "medium" },
        imageUrl: "/courses/bueng-aram/hole-13.jpg",
      },
      {
        number: 14,
        par: 4,
        handicapStroke: 14,
        yardages: { red: 355, white: 378, yellow: 402, blue: 425 },
        waterHazards: { left: false, right: true, front: false },
        bunkers: { positions: ["left", "greenside"], count: 3 },
        green: { shape: "round", size: "medium" },
        holeLayout: { type: "straight", fairwayWidth: "wide" },
        imageUrl: "/courses/bueng-aram/hole-14.jpg",
      },
      {
        number: 15,
        par: 5,
        handicapStroke: 6,
        yardages: { red: 478, white: 502, yellow: 525, blue: 548 },
        waterHazards: { left: true, right: false, front: false },
        bunkers: { positions: ["left", "right", "greenside"], count: 5 },
        green: { shape: "kidney", size: "large" },
        holeLayout: { type: "dogleg-left", fairwayWidth: "medium" },
        imageUrl: "/courses/bueng-aram/hole-15.jpg",
      },
      {
        number: 16,
        par: 3,
        handicapStroke: 18,
        yardages: { red: 152, white: 172, yellow: 188, blue: 205 },
        waterHazards: { left: false, right: true, front: true },
        bunkers: { positions: ["left", "greenside"], count: 2 },
        green: { shape: "round", size: "small" },
        holeLayout: { type: "straight", fairwayWidth: "narrow" },
        imageUrl: "/courses/bueng-aram/hole-16.jpg",
      },
      {
        number: 17,
        par: 4,
        handicapStroke: 2,
        yardages: { red: 385, white: 408, yellow: 432, blue: 455 },
        waterHazards: { left: true, right: false, front: true },
        bunkers: { positions: ["right", "greenside"], count: 4 },
        green: { shape: "oval", size: "medium" },
        holeLayout: { type: "dogleg-right", fairwayWidth: "narrow" },
        imageUrl: "/courses/bueng-aram/hole-17.jpg",
      },
      {
        number: 18,
        par: 5,
        handicapStroke: 10,
        yardages: { red: 485, white: 508, yellow: 532, blue: 555 },
        waterHazards: { left: false, right: true, front: false },
        bunkers: { positions: ["left", "right", "greenside"], count: 5 },
        green: { shape: "round", size: "large" },
        holeLayout: { type: "dogleg-left", fairwayWidth: "wide" },
        imageUrl: "/courses/bueng-aram/hole-18.jpg",
      },
    ];

    return holes;
  },
};
